sudo: required
language: java
jdk: openjdk8

services:
- docker

script:
- "./mvnw clean install -B"

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t xmrcmx/royalcicd:v1 .
- docker push xmrcmx/royalcicd:v1